apiVersion: v1
kind: Service
metadata:
  name: loan-app-load-balancer
  namespace: intel-sgx-loan-app
spec:
  type: LoadBalancer
  selector:
    app: loan-app
  ports:
  - port: 8080
    targetPort: 5000