apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loan-app-pvc-azurefile
  namespace: intel-sgx-loan-app
  labels:
    app: loan-app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: loan-app-pv-azurefile
  resources:
    requests:
      storage: 20Gi